#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)

library(CausalImpact)

x1 <- 100 + arima.sim(model = list(ar = 0.999), n = 100)
y <- 1.2 * x1 + rnorm(100)
y[71:100] <- y[71:100] + 10
data <- cbind(y, x1)

pre.period <- c(1, 70)
post.period <- c(71, 100)

impact <- CausalImpact(data, pre.period, post.period)

#plot(impact)

#summary(impact)

#summary(impact, "report")


# Define UI for application that draws a histogram
ui <- fluidPage(
  

    # Application title
  titlePanel(title=div(img(src="logo.png",align='right'),"Google's Causal Impact")),
    

    # Sidebar with a slider input for number of bins 
    sidebarLayout(
        sidebarPanel(
            fileInput("input",
                        "Upload file to run Causal Impact on:")
        ),

        # Show a plot of the generated distribution
        mainPanel(
          tabsetPanel(type = "tabs",
          tabPanel("Overview",
                   h3('What does this do?'),
                   p('This R package implements an approach to estimating the causal effect of
                   a designed intervention on a time series. For example, how many additional
                   daily clicks were generated by an advertising campaign? Answering a question
                   like this can be difficult when a randomized experiment is not available.'),
                   br(),
                   p('How does it work?'),
                   br(),
                   p('
                     Given a response time series (e.g., clicks) and a set of control time series
                     (e.g., clicks in non-affected markets or clicks on other sites), 
                     the package constructs a Bayesian structural time-series model. 
                     This model is then used to try and predict the counterfactual, 
                     i.e., how the response metric would have evolved after the intervention
                     if the intervention had never occurred.'),
                   h3('Simulated Plot'),
                   plotOutput("distPlot"), 
          ),
           tabPanel("Report",
             verbatimTextOutput("report")
           ),
          )
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {

    output$distPlot <- renderPlot({
      plot(impact)
    })
    
    output$report <- renderPrint({
      summary(impact, "report")
    })
}

# Run the application 
shinyApp(ui = ui, server = server)
